package tech.qijin.study.seata.account.db.model;

public class AccountTbl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tbl.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tbl.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tbl.money
     *
     * @mbg.generated
     */
    private Integer money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tbl.id
     *
     * @return the value of account_tbl.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tbl.id
     *
     * @param id the value for account_tbl.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tbl.user_id
     *
     * @return the value of account_tbl.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tbl.user_id
     *
     * @param userId the value for account_tbl.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tbl.money
     *
     * @return the value of account_tbl.money
     *
     * @mbg.generated
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tbl.money
     *
     * @param money the value for account_tbl.money
     *
     * @mbg.generated
     */
    public void setMoney(Integer money) {
        this.money = money;
    }
}