package tech.qijin.study.seata.account.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import tech.qijin.study.seata.account.db.model.AccountTbl;
import tech.qijin.study.seata.account.db.model.AccountTblExample;

public interface AccountTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_tbl
     *
     * @mbg.generated
     */
    @SelectProvider(type=AccountTblSqlProvider.class, method="countByExample")
    long countByExample(AccountTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_tbl
     *
     * @mbg.generated
     */
    @DeleteProvider(type=AccountTblSqlProvider.class, method="deleteByExample")
    int deleteByExample(AccountTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_tbl
     *
     * @mbg.generated
     */
    @Delete({
        "delete from account_tbl",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_tbl
     *
     * @mbg.generated
     */
    @Insert({
        "insert into account_tbl (user_id, money)",
        "values (#{userId,jdbcType=VARCHAR}, #{money,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(AccountTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_tbl
     *
     * @mbg.generated
     */
    @InsertProvider(type=AccountTblSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(AccountTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_tbl
     *
     * @mbg.generated
     */
    @SelectProvider(type=AccountTblSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="money", property="money", jdbcType=JdbcType.INTEGER)
    })
    List<AccountTbl> selectByExample(AccountTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_tbl
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, user_id, money",
        "from account_tbl",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="money", property="money", jdbcType=JdbcType.INTEGER)
    })
    AccountTbl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_tbl
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AccountTblSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AccountTbl record, @Param("example") AccountTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_tbl
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AccountTblSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AccountTbl record, @Param("example") AccountTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_tbl
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AccountTblSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AccountTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_tbl
     *
     * @mbg.generated
     */
    @Update({
        "update account_tbl",
        "set user_id = #{userId,jdbcType=VARCHAR},",
          "money = #{money,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AccountTbl record);
}