
server:
  port: 10002

spring:
  application:
    name: eureka-provider
#  cloud:
#    config:
#      uri: http://localhost:8888


# logging config
logging:
  config: classpath:log4j2.xml

eureka:
  instance:
    statusPageUrlPath: /actuator
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
    healthcheck: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
