package tech.qijin.study.seata.storage.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import tech.qijin.study.seata.storage.db.model.StorageTbl;
import tech.qijin.study.seata.storage.db.model.StorageTblExample;

public interface StorageTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated
     */
    @SelectProvider(type=StorageTblSqlProvider.class, method="countByExample")
    long countByExample(StorageTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated
     */
    @DeleteProvider(type=StorageTblSqlProvider.class, method="deleteByExample")
    int deleteByExample(StorageTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated
     */
    @Delete({
        "delete from storage_tbl",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated
     */
    @Insert({
        "insert into storage_tbl (commodity_code, count)",
        "values (#{commodityCode,jdbcType=VARCHAR}, #{count,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(StorageTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated
     */
    @InsertProvider(type=StorageTblSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(StorageTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated
     */
    @SelectProvider(type=StorageTblSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="commodity_code", property="commodityCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="count", property="count", jdbcType=JdbcType.INTEGER)
    })
    List<StorageTbl> selectByExample(StorageTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, commodity_code, count",
        "from storage_tbl",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="commodity_code", property="commodityCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="count", property="count", jdbcType=JdbcType.INTEGER)
    })
    StorageTbl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated
     */
    @UpdateProvider(type=StorageTblSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") StorageTbl record, @Param("example") StorageTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated
     */
    @UpdateProvider(type=StorageTblSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") StorageTbl record, @Param("example") StorageTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated
     */
    @UpdateProvider(type=StorageTblSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(StorageTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_tbl
     *
     * @mbg.generated
     */
    @Update({
        "update storage_tbl",
        "set commodity_code = #{commodityCode,jdbcType=VARCHAR},",
          "count = #{count,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(StorageTbl record);
}